spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/campus_lost_db?sslMode=DISABLED
    username: root
    password: admin
    pool:
      enabled: false

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

  jackson:
    date-format: yyyy-MM-dd
    time-zone: America/Guayaquil

  webflux:
    base-path: /api

server:
  port: 8080

logging:
  level:
    org.springframework.web: DEBUG
    reactor.netty: DEBUG

app:
  cors:
    allowed-origins: ${APP_CORS_ALLOWED_ORIGINS:http://localhost:5173,http://localhost:5174}